### ISSUE TITLE
Add CloudFlare 1.1.1.1 / 1.0.0.1 

### ISSUE THREAD

**Issue by Forest14** [dyne/dnscrypt-proxy#13]
CloudFlare has launched its DNS service, announced as the fastest ever, it should be included in the list of options here :)
I am not a developer but a promoter of internet security! 
Here is the link to more info:
https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/
THanks!

**Comment by dapphp** [comment]
@Forest14  I think you're looking for this dnscrypt repo at this point: https://github.com/jedisct1/dnscrypt-proxy/

This one is the 1.9.x branch which doesn't support DNS over HTTPS.

**Comment by jaromil** [comment]
having followed what you are doing in the 2.x branch, by now I'd rather support switching to it. cheers

**Comment by Forest14** [comment]
@dapphp & @jedisct1 : Thanks, I will get there! 👍
