### ISSUE TITLE
New DNS server in Mountain View California

### ISSUE THREAD

**Issue by ex-git** [dyne/dnscrypt-proxy#14]
Just use Google Cloud Platform built this server. No log. Can you add to the list?

Stamp for dnscrypt-proxy 2.x:
sdns://AQcAAAAAAAAAEzEwNC4xOTguMTEwLjExNTo0NDMgg2u3HcgDDo2XsrKL05-UK3r6Z7RGMKwymuTIQ4fQZegkMi5kbnNjcnlwdC1jZXJ0LmRucy5xdWFsaXR5b2xvZ3kuY29t

Parameters for dnscrypt-proxy 1.x:
dnscrypt-proxy --provider-key=836B:B71D:C803:0E8D:97B2:B28B:D39F:942B:7AFA:67B4:4630:AC32:9AE4:C843:87D0:65E8
--resolver-address=104.198.110.115:443
--provider-name=2.dnscrypt-cert.dns.qualityology.com

**Comment by ex-git** [comment]
qualityology.com
I am still using openwrt with 1.x so please also update this list also. Thank you.

**Comment by jedisct1** [comment]
Unfortunately no one is maintaining the CSV file any more as far as I know. Maybe this will happen, and maybe this can be as simple as writing a script that builds it from v2 sources, but such script and maintainer don't exist yet :/

**Comment by jedisct1** [comment]
Can you double check the IP address, port and firewall status?

Looks like it isn't reachable at the moment:

```
[2018-04-04 02:39:22] [ERROR] read udp 192.168.100.4:63038->104.198.110.115:443: i/o timeout
[2018-04-04 02:39:22] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
```

**Comment by ex-git** [comment]
having issue opening 443 port in gcp with their docker image. will see if I can fix it tonight.

**Comment by ex-git** [comment]
finally got it work by removing --net=host  from the installation command. Please use below stamp. 

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEzEwNC4xOTguMTEwLjExNTo0NDMgg2u3HcgDDo2XsrKL05-UK3r6Z7RGMKwymuTIQ4fQZegkMi5kbnNjcnlwdC1jZXJ0LmRucy5xdWFsaXR5b2xvZ3kuY29t

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=836B:B71D:C803:0E8D:97B2:B28B:D39F:942B:7AFA:67B4:4630:AC32:9AE4:C843:87D0:65E8
                 --resolver-address=104.198.110.115:443
                 --provider-name=2.dnscrypt-cert.dns.qualityology.com

**Comment by jedisct1** [comment]
Yay, it works!

And it has been added: https://dnscrypt.info/public-servers

So you should see some traffic soon.

Thanks for setting up this!

**Comment by ex-git** [comment]
Thanks. Can you add it to https://github.com/DNSCrypt/dnscrypt-resolvers?

**Comment by jedisct1** [comment]
Oops, I forgot to `git push`. Done!

**Comment by ex-git** [comment]
Great. Thx.

**Comment by ex-git** [comment]
@jedisct1  can you update qualityology.com to my new server? The old one having some issue and will be shutdown soon. The new server in located in Los Angeles, CA.

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEjE5OC4xNDguMTA1LjIwNjo1MyD-tTPaMp_dne699xaJDFo2VUUeJVwkVejRaHIzidCpOSQyLmRuc2NyeXB0LWNlcnQuZG5zLnF1YWxpdHlvbG9neS5jb20

Parameters for dnscrypt-proxy 1.x:
  dnscrypt-proxy --provider-key=FEB5:33DA:329F:DD9D:EEBD:F716:890C:5A36:5545:1E25:5C24:55E8:D168:7233:89D0:A939
                 --resolver-address=198.148.105.206:53
                 --provider-name=2.dnscrypt-cert.dns.qualityology.com

**Comment by ex-git** [comment]
@jedisct1  thanks. I rebuilt the server and follow https://github.com/jedisct1/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server to restore the key but somehow the public key changed? But I can still connect to the server. Below is the new stamp. Server is up and running now. Thank you.

Stamp for dnscrypt-proxy 2.x:
  sdns://AQcAAAAAAAAAEzE5OC4xNDguMTA1LjIwNjo4NTMgcLFt2QLxD5rsnp4cJjYqIF5zW1C3_9jGXDkTWrwQg5UkMi5kbnNjcnlwdC1jZXJ0LmRucy5xdWFsaXR5b2xvZ3kuY29t
