### ISSUE TITLE
Quad9 dnscrypt-resolvers Information (provider public key)

### ISSUE THREAD

**Issue by adit-s** [dyne/dnscrypt-proxy#18]
Hello. I'm looking for **Quad9 (9.9.9.9)'s** dnscrypt information. It's not included in dnscrypt-resolvers.csv and I haven't been able to locate it anywhere else.
Does anyone know what it is and/or how to find it - specifically the **provider public key**?

===
So far, I've found 
PROVIDER_NAME=2.dnscrypt-cert.quad9.net
RESOLVER_IP=9.9.9.9 -e RESOLVER_PORT=8443
but I can't find the PROVIDER_KEY value.

I want to run the [gists/dnscrypt-proxy](https://hub.docker.com/r/gists/dnscrypt-proxy) docker container which need this information.

Thanks in advance for any assistance or guidance,
AditS

**Comment by jedisct1** [comment]
Seems to be `67c847b8c8758cd120245543be756746df34df1d84c00b8c470368df821d863e`.

**Comment by adit-s** [comment]
Thank-you. That worked. If you can, how/where did you find it?

On another note, I decided not to use the gists/dnscrypt-proxy docker container since it's still running dnscrypt-proxy version 1.9.5. I ended up using rix1337/docker-dnscrypt instead.
I started with the official jedisct1/dnscrypt-server but just couldn't get it run. I'm not sure if I was missing something or there's an issue with the image.
