### ISSUE TITLE
signature does not match using minisign in windows 7 x64

### ISSUE THREAD

**Issue by flzzjw72z** [dyne/dnscrypt-proxy#19]
I get this result after downloading the latest dnscrypt-proxy and get acquainted with the program...

`C:\Users\generic\Downloads>minisign -G
Please enter a password to protect the secret key.

Password:
Password (one more time):
Deriving a key from the password in order to encrypt the secret key... done

The secret key was saved as C:\Users\generic\.minisign\minisign.key - Keep it se
cret!
The public key was saved as minisign.pub - That one can be public.

Files signed using this key pair can be verified with the following command:

minisign -Vm <file> -P RWSrhtlidAACV5p0p84A8xMwgLUCwS9EorqVECrf8XHP2pJ+iSBlKWv1

C:\Users\generic\Downloads>minisign.exe -Vm "dnscrypt-proxy-win64-2.0.25.zip" -P
minisign.pub
base64 conversion failed - was an actual public key given?

C:\Users\generic\Downloads>minisign.exe -Vm "dnscrypt-proxy-win64-2.0.25.zip" -P
RWSrhtlidAACV5p0p84A8xMwgLUCwS9EorqVECrf8XHP2pJ+iSBlKWv1
Signature key id in dnscrypt-proxy-win64-2.0.25.zip.minisig is 79833371EA15D7E4
but the key id in the public key is 5702007462D986AB

C:\Users\generic\Downloads>minisign.exe -Vm "dnscrypt-proxy-win64-2.0.25.zip" -p
minisign.pub
Signature key id in dnscrypt-proxy-win64-2.0.25.zip.minisig is 79833371EA15D7E4
but the key id in the public key is 5702007462D986AB`

What's happening here?

**Comment by jedisct1** [comment]
Wrong repository and duplicate of https://github.com/jedisct1/minisign/issues/54

**Comment by flzzjw72z** [comment]
Hm, yeah, sorry I was in a hurry, I did read the doc but very fast, many things going at once here, too much...

So, yeah it's not working with your file either,  but I think I've imposed a new key of mine by doing minisign -G, how can I reset it all, the options in help don't have a revoke key command as far as I  can tell.

**Comment by jedisct1** [comment]
Just type `minisign -Vm dnscrypt-proxy-win64-2.0.25.zip -P RWTk1xXqcTODeYttYMCMLo0YJHaFEHn7a3akqHlb/7QvIQXHVPxKbjB5`

**Comment by flzzjw72z** [comment]
Yup, this worked. Finally, cool, sorry, using windows means being ultra paranoid...i'm forced to use it until I change video cards, mint 18.x doesn't like my 2 Radeon HD's 7870 in CrossFire and it's a big mess, I got used to game in Linux and it's still a shock treatment to use my last resort partition OS for an extended period.

You have a good day,
Best,
fluzz
