### ISSUE TITLE
How to configure for NextDNS

### ISSUE THREAD

**Issue by castillofrancodamian** [dyne/dnscrypt-proxy#23]
I have the app in OpenWrt and I don't know how to configure it with this provider.

**Comment by lnslbrty** [comment]
I also use this software, but I fear that this repository/mirror is pretty much dead.

**Comment by castillofrancodamian** [comment]
It seems 😔😔😔

**Comment by lnslbrty** [comment]
I've already wrote to info@dyne.org, but got no answer. :sob:

**Comment by castillofrancodamian** [comment]
This is discontinued.
